### ISSUE TITLE
Support for per-client limits

### ISSUE THREAD

**Issue by sidprak** [EvoluxBR/python-redis-rate-limit#19]
Currently, a new rate limiter has to be created to have a separate limit per-client. Would you accept a PR to support per-client rate limits? I would add a check in the constructor [here](https://github.com/EvoluxBR/python-redis-rate-limit/blob/master/redis_rate_limit/__init__.py#L65). If the `max_requests` is a dict, it will be treated as a mapping between client and max_requests for that client. Otherwise, it will be a global limit.

**Comment by italorossi** [comment]
Hi there,

You can use the RateLimiter for this:
```python
base_limiter = RateLimiter(resource='test', max_requests=10, expire=2)
client1_limiter = base_limiter.limit(client='localhost')
client2_limiter = base_limiter.limit(client='10.10.10.10')

with client1_limiter:
    do_something()

with client2_limiter:
    do_another_thing()
```
