### ISSUE TITLE
Testing requires a live Redis server

### ISSUE THREAD

**Issue by phrfpeixoto** [EvoluxBR/python-redis-rate-limit#23]
I'll try to implement a way so we can mock the redis.

This shouldn't require a live server for testing.

**Comment by victor-torres** [comment]
I don't see this requirement as a problem. In fact, it's actually good IMO to use a real Redis server as it makes the test cases closer to the real-world scenarios and makes it possible to discover bugs beforehand. Also, the tests take about one minute in total to be completed, so it wouldn't be a huge improvement in terms of performance to justify this change.

**Comment by ehiggs-deliverect** [comment]
You could use [pytest-redis which allows you to test against a RedisDB](https://pypi.org/project/pytest-redis/) that is spawned either per function, per test run, or just uses an existing one.

**Comment by italorossi** [comment]
I'll go ahead and close this one since requiring a live Redis server is not a big problem at this moment. I like the pytest-redis idea, thanks for the suggestion @ehiggs-deliverect .
