### ISSUE TITLE
Add support for bulk increment usage

### ISSUE THREAD

**Issue by tcnleung** [EvoluxBR/python-redis-rate-limit#25]
The rate limiter should have the ability to increase usage in bulk. This will allow the rate limit to assign different weights to different requests which will make the rate limiter more versatile. 

This feature entails adding a Lua script to use incrby instead of incr and being able to pass in an argument to the script that will be used to increase the count.

**Comment by victor-torres** [comment]
It seems like the pull request #16 is implementing this usage. 

cc @italorossi

**Comment by italorossi** [comment]
Yes, it does. I'll merge it and update the code according to the last comments there.

**Comment by charleswhchan** [comment]
@italorossi : That would be awesome. Looking forward to the upcoming release. 👍

**Comment by italorossi** [comment]
Changes pushed.
