### ISSUE TITLE
AWS ElastiCache support

### ISSUE THREAD

**Issue by YouJinTou** [EvoluxBR/python-redis-rate-limit#33]
`
        redis_version = self._redis.info['redis_version']
        is_supported = Version(str(redis_version)) >= Version('2.6.0')`

This does not work on Amazon's ElastiCache as `redis_version` is a number, and `Version()` blows up with `expected string or a byte-like object...`.

**Comment by victor-torres** [comment]
I think this is fixed by #34

**Comment by italorossi** [comment]
https://pypi.org/project/python-redis-rate-limit/0.0.10/
